/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ManualReviewRouteImport } from './routes/manual-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ClickupRouteImport } from './routes/clickup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailsIdRouteImport } from './routes/emails.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualReviewRoute = ManualReviewRouteImport.update({
  id: '/manual-review',
  path: '/manual-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickupRoute = ClickupRouteImport.update({
  id: '/clickup',
  path: '/clickup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIdRoute = EmailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clickup': typeof ClickupRoute
  '/emails': typeof EmailsRouteWithChildren
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clickup': typeof ClickupRoute
  '/emails': typeof EmailsRouteWithChildren
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clickup': typeof ClickupRoute
  '/emails': typeof EmailsRouteWithChildren
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clickup'
    | '/emails'
    | '/login'
    | '/manual-review'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/emails/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clickup'
    | '/emails'
    | '/login'
    | '/manual-review'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/emails/$id'
  id:
    | '__root__'
    | '/'
    | '/clickup'
    | '/emails'
    | '/login'
    | '/manual-review'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/emails/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClickupRoute: typeof ClickupRoute
  EmailsRoute: typeof EmailsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManualReviewRoute: typeof ManualReviewRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-review': {
      id: '/manual-review'
      path: '/manual-review'
      fullPath: '/manual-review'
      preLoaderRoute: typeof ManualReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clickup': {
      id: '/clickup'
      path: '/clickup'
      fullPath: '/clickup'
      preLoaderRoute: typeof ClickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$id': {
      id: '/emails/$id'
      path: '/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof EmailsIdRouteImport
      parentRoute: typeof EmailsRoute
    }
  }
}

interface EmailsRouteChildren {
  EmailsIdRoute: typeof EmailsIdRoute
}

const EmailsRouteChildren: EmailsRouteChildren = {
  EmailsIdRoute: EmailsIdRoute,
}

const EmailsRouteWithChildren =
  EmailsRoute._addFileChildren(EmailsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClickupRoute: ClickupRoute,
  EmailsRoute: EmailsRouteWithChildren,
  LoginRoute: LoginRoute,
  ManualReviewRoute: ManualReviewRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
